function plotSensor(point,style)

%midpoint = [point(1,1);point(2,1);point(3,1);]+[point(1,2);point(2,2);point(3,2);]/2;
%Create the normalized matrix of the points.
%The format of the points 
%[ cvt.rightback;
% cvt.leftback;
% cvt.front;
% cvt.crosspoint];
rightback = point(1:3,1);
leftback = point(1:3,2);
front = point(1:3,3);
crosspoint = point(1:3,4);
midpoint = (rightback+leftback)/2;

plot3(... 
    [leftback(1),rightback(1),midpoint(1),front(1),midpoint(1),crosspoint(1)],...
    [leftback(2),rightback(2),midpoint(2),front(2),midpoint(2),crosspoint(2)],...
    [leftback(3),rightback(3),midpoint(3),front(3),midpoint(3),crosspoint(3)],style,...
    crosspoint(1),...
    crosspoint(2),...
    crosspoint(3),'rx',...
    leftback(1),...
    leftback(2),...
    leftback(3),'ro',...
    rightback(1),...
    rightback(2),...
    rightback(3),'go',...
    front(1),...
    front(2),...
    front(3),'bo','MarkerSize',20);
end